// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.SheetComponents.AbilityScore.#ctor(RoleplayingGame.Objects.Actor,RoleplayingGame.Enums.Ability,System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.AbilityInfoAttribute.#ctor(RoleplayingGame.Enums.AbilityGroup,RoleplayingGame.Enums.AbilityType,FChatApi.Enums.BBCodeColor)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.ActionDefaultValuesAttribute.#ctor(RoleplayingGame.Enums.Ability[],System.Int32,System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.ActionPropertiesAttribute.#ctor(System.Boolean,System.Single,RoleplayingGame.Enums.GameAction)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.DefaultModifierAttribute.#ctor(System.Single)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.DerivedAbilityInfoAttribute.#ctor(RoleplayingGame.Enums.Ability[],RoleplayingGame.Enums.AbilityGroup,RoleplayingGame.Enums.AbilityType)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.EchelonPropertiesAttribute.#ctor(System.Int16,RoleplayingGame.Enums.GameAction)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.GameFlagsAttribute.#ctor(System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.ResourceDefaultValuesAttribute.#ctor(System.Int32,System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.ShortFormAttribute.#ctor(System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Attributes.XmlKeyAttribute.#ctor(System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Effects.AttackChassis.#ctor(RoleplayingGame.Enums.AttackType,System.String,System.Single,System.Single,System.Single,System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Ability,System.Single},System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Ability,System.Single},System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Ability,System.Single},RoleplayingGame.Enums.StatusEffect[])")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.Effects.AttackEvent.#ctor(RoleplayingGame.Objects.Actor,RoleplayingGame.Enums.EnvironmentSource,RoleplayingGame.Objects.Actor,System.Single,System.Single,System.Single,RoleplayingGame.Effects.ActiveStatusEffect[])")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.SheetComponents.CharacterClass.#ctor(RoleplayingGame.Enums.ClassName,System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Resource,System.Collections.Generic.Dictionary{RoleplayingGame.Enums.ResourceModifier,System.Single}},System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Resource,System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Ability,System.Single}},System.Collections.Generic.Dictionary{RoleplayingGame.Enums.Ability,System.Single})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.SheetComponents.CharacterResource.#ctor(RoleplayingGame.Objects.Actor,System.Int32,System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:RoleplayingGame.SheetComponents.ResourceBase.#ctor(RoleplayingGame.Objects.Actor,System.Int32,System.Int32,System.Boolean)")]
